# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  secret_key_base: 7ffdf06cc326b0a28c97b2bba8458d23ef18be3532ea59719844599287c63e6cf4ca04984bcf9b859e2d3feac8914c1d5100d9616036823a7793e248ab7151f8
  devise_secret_key: d836ea3f57cc1f9390b043aabce1f094c69c3c31e9d6230015a470e48fdf5551f0db36aace8d556f169e1bf1aca590a29e9a16237f2f181b2e28068b19677b78
  new_relic_license_key: c2f6766d57a50a2ac72ec247a44b17c0abc7dc45
  import_feed_url: "http://pipes.yahoo.com/pipes/pipe.run?_id=1a1d51df4a9146f63008151add13f5f1&_render=rss"
  domain_name: localhost:3000
  http_basic_auth:
    username: admin
    password: noataner

development:
  <<: *default

test:
  <<: *default

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  devise_secret_key: <%= ENV['SECRET_KEY_BASE'] %>
  new_relic_license_key: <%= ENV['NEW_RELIC_LICENSE_KEY'] %>
  domain_name: <%= ENV['DOMAIN_NAME'] %>

staging:
  <<: *default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  devise_secret_key: <%= ENV['SECRET_KEY_BASE'] %>
  new_relic_license_key: <%= ENV['NEW_RELIC_LICENSE_KEY'] %>
  domain_name: <%= ENV['DOMAIN_NAME'] %>
